### ISSUE TITLE
MarkAPL.dws is saved in version 17.0 (beta)

### ISSUE THREAD

**Issue by abrudz** [aplteam/MarkAPL#14]
Which means it cannot currently be used in any supported version.

I recommend saving it in 15.0 as that will soon be Dyalog's oldest supported version.

Try `]version path/MarkAPL.dws`

**Comment by aplteam** [comment]
The real problem is that the workspace should not be part of the project on GitHub at all. It should be mentionend in gitignore. The whole purpose of moving to GitHub was to get rid of workspaces altogether.
